management:
  health:
    bulkhead:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  bulkhead:
    instances:
      userService:
        maxWaitDuration: 1ms
        maxConcurrentCalls: 3
        
#resilience4j.thread-pool-bulkhead:
 # instances:
  #  userService:
   #   maxThreadPoolSize: 1
    #  coreThreadPoolSize: 1
     # queueCapacity: 1