spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis_server
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver   
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  #Redis cache config
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    
    password:
  application:
    name: redis-demo-service
server:
  port: 9001